development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: my_database
  pool: 5
  username: benjaminbenoudis
  password: jetaime
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000